### ISSUE TITLE
Mutual Information Implementation

### ISSUE THREAD

**Issue by danaderp** [WM-SEMERU/ds4se#69]
- [x] Organize benchmarking folder in main into dvc-ds4se
- [x] Rename cisco params to sacp params
- [x] Create a sheet with all the experiments 
- [ ] Use BPEs trained by Nathan (latest BPEs)

**Comment by danielrcardenas** [comment]
Adding tasks

- [ ] Update python notebook name for standars

- [ ] Validate alphabet length source vs target at w2v

- [ ] Split doc2vect from w2v notebook

- [ ] At computeDistanceArtifacts load W2v (optional)

**Comment by danaderp** [comment]
The latest BPEs generated by @ncoop57 were not taking into account for Information Science on IR experiment.  We use a standard sentence piece.
