### ISSUE TITLE
Evaluating Information Manifold Metrics

### ISSUE THREAD

**Issue by danaderp** [WM-SEMERU/ds4se#84]
- [x]  Experiments 0.0.x Baselines
- [x]  Experiments 1.0.x 
- [x]  Experiments 1.x.x
- [x]  Experiments 2.x.x
- [x]  Experiments 3.x.x

**Comment by danaderp** [comment]
The statistical module was implemented. Some baselines were generated. However, we are waiting for all experiments to finish.

**Comment by danielrcardenas** [comment]
Getting started with  statistical analysis for those experiments that already finished ( still running sacp 32 and 128k)

- [ ]  Evaluation 0.0.x Baselines
- [ ]  Evaluation 1.0.x
- [ ]  Evaluation 1.x.x
- [ ]  Evaluation 2.x.x
- [ ]  Evaluation 3.x.x

**Comment by danielrcardenas** [comment]
@danaderp Closing this issue an opening a new one for BPE and another one for statistical analysis
