### ISSUE TITLE
[Alvaro] SE Metrics Module Implemented

### ISSUE THREAD

**Issue by danaderp** [WM-SEMERU/ds4se#89]
Please implement or refactor a module whose purpose is to measure common SE metrics for python and java. 

- [x] Create the classes and interfaces to consume SE metrics for Java
- [x] Create the classes and interfaces to consume SE metrics for Python
- [x] Create a separate notebook that consumes the previous interfaces and test the functionality under a tutorial format.

**Comment by danaderp** [comment]
@ncoop57 Alvaro is working on a well-organized module for SE metrics.

**Comment by aldrodriguezca** [comment]
@danaderp, @ncoop57 the modules are available at the ds4se container, please review them. I'm looking forward to your comments.

The corresponding notebooks are:

0.7_metrics_module_python
0.8_metrics_module_java
0.9_metrics_example

**Comment by danaderp** [comment]
Documentation completed!
